livox_perception_node:
  ros__parameters:
    lidar_topic: "/iv_points"
    output_frame: "center_camera"
    grid_resolution: 0.1
    grid_width: 30.0
    grid_height: 6.0
    grid_origin_x: -15.0
    grid_origin_y: -3.0
    grid_origin_z: -2.0
    min_distance: 0.1
    max_forward: 15.0
    max_backward: 15.0
    max_left: 5.0
    max_right: 5.0
    min_height: -0.2
    max_height: 1.5
    invalid_rect_front: 0.1
    invalid_rect_back: 0.6
    invalid_rect_right: 0.6
    invalid_rect_left: 0.0
    voxel_leaf_size: 0.1
    tracker_occupancy_increase: 0.7
    tracker_decay: 0.5
    tracker_min_probability: 0.1
    tracker_max_probability: 0.98
    tracker_occupied_threshold: 0.65
    lidar_to_camera_extrinsic: [0.0084909, -0.999892, -0.012023, 0.025, 0.00134585, 0.0120348,
      -0.999927, 0.046, 0.999963, 0.00847409, 0.00144789, 0.0, 0.0, 0.0, 0.0, 1.0]
    calibration_file: "calibration/front_left.yaml"
    pointcloud_topic: "/livox/camera_points"
    log_directory: "logs"
